# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Rocksclusters website
email: admin@rocksclusters.org
description: > # this means to ignore newlines until "baseurl:"
  Rocksclusters website
baseurl: "" # the subpath of your site, e.g. /blog

# enable when done
#url: "http://www.rocksclusters.org" # the base hostname & protocol for your site
github_username:  rocksclusters

github_url: "https://github.com/rocksclusters"

# Build settings
markdown: kramdown

collections: 
  downloads:
      output: true
  support:
      output: true


exclude:
  - README
  - Makefile
  - server.sh
  - junk/
